# Smartchime Configuration

# MQTT Connection Settings
mqtt:
  # MQTT broker hostname or IP address
  # Default: localhost
  broker: localhost

  # MQTT broker port number
  # Default: 1883
  # Common alternatives: 8883 (TLS)
  port: 1883

  # MQTT authentication credentials
  # Leave empty for no authentication
  # Default: empty (no authentication)
  username: ""
  password: ""

  # MQTT topics for system events
  topics:
    # Topic for doorbell ring events
    # Payload format: {"active": bool, "timestamp": "ISO8601", "video_url": "string"}
    doorbell: smartchime/doorbell/ring

    # Topic for motion detection events
    # Payload format: {"active": bool, "timestamp": "ISO8601", "video_url": "string"}
    motion: smartchime/motion/detected

    # Topic for displaying custom messages on OLED
    # Payload format: {"text": "string"} or plain string
    message: smartchime/display/message

# Audio System Configuration
audio:
  # Directory containing WAV sound files for doorbell
  # Must be absolute path with read permissions
  directory: /path/to/audio/files

  # Default sound file to play on doorbell events
  # Must be a .wav file present in the audio directory
  default_sound: doorbell.wav

  # ALSA mixer configuration
  mixer:
    # ALSA mixer device name
    # Default: snd_rpi_hifiberry_dacplus
    # Use 'aplay -l' to list available devices
    device: snd_rpi_hifiberry_dacplus

    # ALSA mixer control name
    # Default: PCM
    # Common alternatives: Master, Speaker, Headphone
    control: Digital

# Video Stream Configuration
video:
  # Default video stream URL for doorbell camera
  # Supports rtsp://, http://, or local device paths
  default_stream: http://your-camera-stream-url

# Display Device Configuration
displays:
  # HDMI display settings
  hdmi:
    # Linux framebuffer device for video output
    # Default: /dev/fb0
    # Requires read/write permissions
    framebuffer: /dev/fb0  # Framebuffer device for direct output

  # OLED display settings (SSD1305)
  oled:
    # SPI port number
    # Default: 0 (Connected to SPI0 on Raspberry Pi)
    spi_port: 0
    # OLED display device number (usually 0)
    spi_device: 0

# GPIO Pin Configuration
gpio:
  # Volume control rotary encoder
  volume_encoder:
    # GPIO pin numbers in BCM mode
    clk: 15  # Clock signal pin
    dt: 23   # Data signal pin
    sw: 14   # Switch/button pin

  # Sound selection rotary encoder
  sound_select_encoder:
    # GPIO pin numbers in BCM mode
    clk: 27  # Clock signal pin
    dt: 22   # Data signal pin
    sw: 17   # Switch/button pin

# Shairport Sync AirPlay Configuration
shairport:
  # Path to Shairport Sync metadata pipe
  # Default: /tmp/shairport-sync-metadata
  # Must match Shairport Sync configuration
  metadata_pipe: /tmp/shairport-sync-metadata

  # Duration in seconds to show track information
  # Default: 10
  # Set to 0 to disable automatic hiding
  show_duration: 10  # How long to show the track info before returning to normal display